import React from 'react';
import styles from './Skills.module.css';
import { SiPhp } from 'react-icons/si';
import {
  SiReact,
  SiNodedotjs,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiTypescript,
  SiNextdotjs,
  SiAngular,
  SiExpress,
  SiPython,
  SiGithub,
  SiMongodb,
  SiMysql,
  SiDocker,
  SiLinux,
  SiJenkins,
  SiGoogleanalytics,
  SiElectron,
  SiSpring,
  SiUbuntu,
  SiJson,
  SiScikitlearn,
  SiPostgresql,
  SiRedis,
  SiElastic,
  SiRabbitmq,
  SiJsonwebtokens,
  SiVuedotjs,
  SiNestjs,
  SiTensorflow,
  SiTailwindcss,
  SiNginx,
  SiAmazonaws,
  SiPm2,
  SiFilezilla,
  SiPhpmyadmin,
  SiLua,
} from 'react-icons/si';
import { DiJava, DiTerminal } from 'react-icons/di';
import {
  FaTools,
  FaBullhorn,
  FaNetworkWired,
  FaServer,
  FaClipboardCheck,
  FaCloud,
  FaFileCode,
  FaSitemap,
  FaCogs,
  FaRocket,
  FaProjectDiagram,
  FaSyncAlt,
  FaBrain,
  FaListUl,
  FaMicrochip,
  FaPaintBrush,
  FaCode,
  FaCalculator,
  FaLightbulb,
  FaMobileAlt,
  FaUserSecret,
  FaDatabase,
  FaTable,
  FaCar,
  FaGlobe,
  FaComments,
  FaRobot,
  FaChartLine,
  FaGem,
  FaCube,
  FaEdit,
  FaGlobeAmericas,
  FaGlobeEurope,
} from 'react-icons/fa';

const skills = [
  { name: 'React', icon: <SiReact size={70} /> },
  { name: 'Angular', icon: <SiAngular size={70} /> },
  { name: 'Vue.js', icon: <SiVuedotjs size={70} /> },
  { name: 'Next.js', icon: <SiNextdotjs size={70} /> },
  { name: 'HTML', icon: <SiHtml5 size={70} /> },
  { name: 'CSS', icon: <SiCss3 size={70} /> },
  { name: 'JavaScript', icon: <SiJavascript size={70} /> },
  { name: 'TypeScript', icon: <SiTypescript size={70} /> },
  { name: 'Tailwind CSS', icon: <SiTailwindcss size={70} /> },
  { name: 'UI/UX', icon: <FaMobileAlt size={70} /> },
  { name: 'Node.js', icon: <SiNodedotjs size={70} /> },
  { name: 'Express', icon: <SiExpress size={70} /> },
  { name: 'NestJS', icon: <SiNestjs size={70} /> },
  { name: 'Python', icon: <SiPython size={70} /> },
  { name: 'Java', icon: <DiJava size={70} /> },
  { name: 'Java Spring', icon: <SiSpring size={70} /> },
  { name: 'MongoDB', icon: <SiMongodb size={70} /> },
  { name: 'MySQL', icon: <SiMysql size={70} /> },
  { name: 'PostgreSQL', icon: <SiPostgresql size={70} /> },
  { name: 'Redis', icon: <SiRedis size={70} /> },
  { name: 'ElasticSearch', icon: <SiElastic size={70} /> },
  { name: 'RabbitMQ', icon: <SiRabbitmq size={70} /> },
  { name: 'phpMyAdmin', icon: <SiPhpmyadmin size={70} /> },
  { name: 'DBeaver', icon: <FaTable size={70} /> },
  { name: 'Docker', icon: <SiDocker size={70} /> },
  { name: 'CI/CD', icon: <FaSyncAlt size={70} /> },
  { name: 'DevOps', icon: <FaTools size={70} /> },
  { name: 'Cloud Computing', icon: <FaCloud size={70} /> },
  { name: 'Linux', icon: <SiLinux size={70} /> },
  { name: 'VPS', icon: <FaServer size={70} /> },
  { name: 'Ubuntu Server', icon: <SiUbuntu size={70} /> },
  { name: 'SSH', icon: <DiTerminal size={70} /> },
  { name: 'Nginx', icon: <SiNginx size={70} /> },
  { name: 'AWS', icon: <SiAmazonaws size={70} /> },
  { name: 'PM2', icon: <SiPm2 size={70} /> },
  { name: 'FTP', icon: <SiFilezilla size={70} /> },
  { name: 'Monolith', icon: <FaCube size={70} /> },
  { name: 'Manual Testing', icon: <FaEdit size={70} /> },
  { name: 'Lua', icon: <SiLua size={70} /> },
  { name: 'Electron', icon: <SiElectron size={70} /> },
  { name: 'Git/GitHub', icon: <SiGithub size={70} /> },
  { name: 'JWT', icon: <SiJsonwebtokens size={70} /> },
  { name: 'JSON', icon: <SiJson size={70} /> },
  { name: 'XML', icon: <FaFileCode size={70} /> },
  { name: 'SKLearn', icon: <SiScikitlearn size={70} /> },
  { name: 'REST APIs', icon: <FaNetworkWired size={70} /> },
  { name: 'SEO', icon: <SiGoogleanalytics size={70} /> },
  { name: 'Digital Marketing', icon: <FaBullhorn size={70} /> },
  { name: 'Automated Testing', icon: <FaClipboardCheck size={70} /> },
  { name: 'Clean Code', icon: <FaLightbulb size={70} /> },
  { name: 'Clean Architecture', icon: <FaLightbulb size={70} /> },
  { name: 'Ethical Hacker', icon: <FaUserSecret size={70} /> },
  { name: 'Class Diagram', icon: <FaSitemap size={70} /> },
  { name: 'Database Diagram', icon: <FaDatabase size={70} /> },
  { name: 'Data Communication', icon: <FaComments size={70} /> },
  { name: 'Robotics', icon: <FaRobot size={70} /> },
  { name: 'Statistics', icon: <FaChartLine size={70} /> },
  { name: 'Data Mining', icon: <FaGem size={70} /> },
  { name: 'Use Case Diagram', icon: <FaSitemap size={70} /> },
  { name: 'OOP', icon: <FaCogs size={70} /> },
  { name: 'Agile Methodologies', icon: <FaRocket size={70} /> },
  { name: 'Software Engineering', icon: <FaTools size={70} /> },
  { name: 'Algorithms', icon: <FaBrain size={70} /> },
  { name: 'Data Structures', icon: <FaListUl size={70} /> },
  { name: 'Computer Architecture', icon: <FaMicrochip size={70} /> },
  { name: 'Computer Networks', icon: <FaNetworkWired size={70} /> },
  { name: 'Artificial Intelligence', icon: <SiTensorflow size={70} /> },
  { name: 'Computer Graphics', icon: <FaPaintBrush size={70} /> },
  { name: 'Functional Programming', icon: <FaCode size={70} /> },
  { name: 'Discrete Mathematics', icon: <FaCalculator size={70} /> },
  { name: 'Microservices', icon: <FaProjectDiagram size={70} /> },
  { name: "Driver's License", icon: <FaCar size={70} /> },
  { name: 'Fluent English', icon: <FaGlobe size={70} /> },
  { name: 'Fluent Portuguese', icon: <FaGlobeAmericas size={70} /> },
  { name: 'Basic German', icon: <FaGlobeEurope size={70} /> },
];

function Skills() {
  return (
    <div className={styles.blueContainer}>
      <h2>Skills</h2>
      <ul className={styles.skillsList}>
        {skills.map((skill, index) => (
          <li key={index}>
            {skill.icon}
            <p>{skill.name}</p>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default Skills;
